name: (Post-PR Approval) - Build and Push Docker Image

on:
  workflow_run:
      workflows: ["(Health Check) main - Pull Request"]
      types:
          - completed

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest .

      - name: Tag Docker image with version
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${VERSION}

      - name: Push Docker image to DockerHub (latest)
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      - name: Push Docker image to DockerHub (versioned)
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${VERSION}
