name: 🛡️ (Code Health Check - Main)

on:
  pull_request_target:
    types:
      - reopened
      - synchronize
  pull_request:
    types:
      - opened
    branches:
      - 'main'

permissions:
  pull-requests: write
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

jobs:
  inform:
    name: 🚀 Initializing Code Health Check
    runs-on: ubuntu-latest
    steps:
      - name: 📢 Start PR Validation
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ## 🚦 Pull Request Validation Initialized
            🔍 Validating committed files.
            
            🛠️ **Jobs Running** - *Please wait for the results below...*

            🚀 **Triggered by**: @${{ github.actor }}, via *${{ github.event_name }}*

  security_check:
    needs: inform
    name: 🔐 Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: 🔎 Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Run security audit
        id: security-audit
        run: npm audit --audit-level=high

      - name: 🛡️ Post Security Audit Failure
        if: steps.security-audit.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ## ⚠️ Security Audit Failed!
            🚨 High or critical vulnerabilities were found.
            
            Please review the audit results and fix the issues:
            ```
            npm audit results...
            ```

  quality_check:
    needs: security_check
    name: ✅ Code Quality and Testing
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run Automated Tests
        id: automated-tests
        run: npm test

      - name: 🛠️ SonarCloud Quality Gate
        id: sonar-quality-gate
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:          
          args: >
            -Dsonar.projectKey=${{ vars.PROJECT_KEY }}
            -Dsonar.organization=${{ vars.ORGANIZATION }}
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.exclusions=node_modules/**,src/main/**,src/core/**,src/domain/**,src/adapters/**,**\*.spec.ts,**\*.test.ts,
            -Dsonar.typescript.tsconfigPath=tsconfig.json
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.verbose=true

      - name: 🚨 Post Test Failure
        if: steps.automated-tests.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ## ❌ Test Failure!
            ### 🚨 Tests failed in the PR validation process.
            
            Review the errors below:
            ```
            Test error details here...
            ```

      - name: 🚨 Post Quality Gate Failure
        if: steps.sonar-quality-gate.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ## ❌ SonarCloud Quality Gate Failed!
            ### 🚨 Code Quality Analysis Failed!
            
            Review the issues identified:
            ```
            SonarCloud quality details here...
            ```

      - name: 🟢 All Tests Passed!
        if: success()
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ## 🎉 Code Validation Successful!
            ### ✅ All tests and quality checks have passed.
            
            You can merge this pull request safely! 🚀
